import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Dự án Cù lao An Bình chứng ngộ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
        <footer
          className={cn(
            "flex justify-center items-center h-12 bg-gray-100 text-gray-500"
          )}
        >
          <p>© {new Date().getFullYear()} Novita Group</p>
        </footer>
      </body>
    </html>
  );
}
